father('Sergey Moskvin','Stanislav Moskvin').
father('Nikolai Bashkin','Valentina Moskvina').
father('Aleksey Nikitnikov','Viktor Nikitnikov').
father('Nikolai Abramov','Lidia Nikitnikova').
father('Stanislav Moskvin','Artur Moskvin').
father('Viktor Nikitnikov','Elena Moskvina').
father('Viktor Nikitnikov','Dmitriy Nikitnikov').
father('Viktor Nikitnikov','Irina Shulgina').
father('Artur Moskvin','Artem Moskvin').
father('Dmitriy Nikitnikov','Ivan Nikitnikov').
father('Dmitriy Nikitnikov','Alisa Nikitnikova').
father('Dmitriy Nikitnikov','Stepan Nikitnikov').
father('Ilia Shulgin','Sofia Shulgina').
father('Ilia Shulgin','Vera Shulgina').

mother('Ksenia Moskvina','Stanislav Moskvin').
mother('Tatiana Bashkina','Valentina Moskvina').
mother('Maria Nikitnikova','Viktor Nikitnikov').
mother('Klavdia Abramova','Lidia Nikitnikova').
mother('Valentina Moskvina','Artur Moskvin').
mother('Lidia Nikitnikova','Elena Moskvina').
mother('Lidia Nikitnikova','Dmitriy Nikitnikov').
mother('Lidia Nikitnikova','Irina Shulgina').
mother('Elena Moskvina','Artem Moskvin').
mother('Julia Nikitnikova','Ivan Nikitnikov').
mother('Julia Nikitnikova','Alisa Nikitnikova').
mother('Julia Nikitnikova','Stepan Nikitnikov').
mother('Irina Shulgina','Sofia Shulgina').
mother('Irina Shulgina','Vera Shulgina').

